### ISSUE TITLE
can‘t run each prject

### ISSUE THREAD

**Issue by XuankeShi** [alleboudy/detectozord#1]
i don’t know why ，but i think your project can not work

**Comment by alleboudy** [comment]
Could you share more details? 
If you aren't able to run any of the projects, this clearly indicates a lack of experience with cmake or a broken development environment.
Kindly, 
1- Make sure the environment is set as described in the readme and validate the installation of each tool separately.
2- Share the errors you are facing when running any of the projects.

Thanks.
