### ISSUE TITLE
when

### ISSUE THREAD

**Issue by XuankeShi** [alleboudy/detectozord#2]
Hi,when i cmake execise6 , cmake can't find the package OPENNI2,but i've install the openni2,I don't know why? and i want to get your help.
The error as follows:
-----------------------------------------------------------------------------
 CMake Warning at CMakeLists.txt:30 (find_package):
  By not providing "Findopenni2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "openni2", but
  CMake did not find one.

  Could not find a package configuration file provided by "openni2" with any
  of the following names:

    openni2Config.cmake
    openni2-config.cmake

  Add the installation prefix of "openni2" to CMAKE_PREFIX_PATH or set
  "openni2_DIR" to a directory containing one of the above files.  If
  "openni2" provides a separate development package or SDK, be sure it has
  been installed.

CMake Error at CMakeLists.txt:36 (find_package):
  By not providing "FindOPENNI2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OPENNI2", but
  CMake did not find one.

  Could not find a package configuration file provided by "OPENNI2" with any
  of the following names:

    OPENNI2Config.cmake
    openni2-config.cmake

  Add the installation prefix of "OPENNI2" to CMAKE_PREFIX_PATH or set
  "OPENNI2_DIR" to a directory containing one of the above files.  If
  "OPENNI2" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by alleboudy** [comment]
As the cmake error points out the issue, openni2 is not on the system path.
Are you able to verify the installation by capturing a video via the sample tool provided by openni2 for validation?
https://structure.io/openni
Please follow the installation instructions provided by the authors of the library closely, I will not be able to provide better support than theirs.

Google keyword: openni2 installation [your OS]

Kindly, please understand that I will only be able to help with the actual work done in this repository [adapting new training data, changing the PointNet model, pointing out utility functions or highlighting and explaining ambiguous functionalities that I wrote.
 Environment setup, however, is out of the scope and won't be any better than the authors of the tools themselves.]
Please refer to the official websites of the tools used for the environment setup of your OS 
https://cmake.org/
http://www.pointclouds.org/downloads/
https://opencv.org/
https://www.tensorflow.org/

Thanks.
